name: Lighthouse
on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          branch: main
          emulatedFormFactor: 'desktop'
          urls: 'https://geofood-delivery.herokuapp.com'
