name: Puppeteer tests
on: push

jobs:
  build:
    name: Puppeteer tests
    # Tell the action to use the latest
    # version of Ubuntu (a Linux flavor)
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    env:
      PGHOST: localhost
      PGDATABASE: ${{ secrets.PGDATABASE }}
      PGUSERNAME: ${{ secrets.PGUSERNAME }}
      PGPASSWORD: ${{ secrets.PGPASSWORD }}
      CSRF_SECRET_SALT: ${{ secrets.CSRF_SECRET_SALT }}
    steps:
      - name: Start preinstalled PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      - name: Create database user
        run: |
          sudo -u postgres psql --command="CREATE USER ${{ secrets.PGUSERNAME }} PASSWORD '${{ secrets.PGPASSWORD }}'" --command="\du"
      - name: Create database and allow user
        run: |
          sudo -u postgres createdb --owner=${{ secrets.PGUSERNAME }} ${{ secrets.PGDATABASE }}
      - name: Create extension
        run: |
          sudo -u postgres psql --command="CREATE EXTENSION postgis;" --dbname=${{ secrets.PGDATABASE }}
      # Use the official Checkout action (clones the GitHub repo):
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # Use the official setup-node action (sets up Node.js):
      # https://github.com/actions/setup-node
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
      # Run the migrations
      - run: yarn migrate up
      # Build the Next.js application
      - run: yarn build
      # Run the Jest unit tests
      - run: yarn jest --config integration/jest.config.mjs
