#.github/workflows/yarn-audit-action.yaml
name: Yarn-Audit
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yarn Audit
        uses: pragatheeswarans/yarn-audit-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # assignee: 'ASSIGNEE NAME'
          label: 'LABEL'
          title: 'ISSUE TITLE'
          description: 'ISSUE DESCRIPTION'
          # paths: |
          #   .
          #   folder-1
